// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMQb4wT0N0YdsI5G20hv85eC-LylWLAw',
    appId: '1:3090220135:web:9c4d74fe6f2c4d0eb200c2',
    messagingSenderId: '3090220135',
    projectId: 'advmobprog-firebase-bf756',
    authDomain: 'advmobprog-firebase-bf756.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-bf756.firebasestorage.app',
    measurementId: 'G-4NL7X9B0PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsWJww-panftOSpDCYbrTg_I2RGqXhC4Q',
    appId: '1:3090220135:android:5b17722650f902b8b200c2',
    messagingSenderId: '3090220135',
    projectId: 'advmobprog-firebase-bf756',
    storageBucket: 'advmobprog-firebase-bf756.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLs9nfut23AJa4Lz1df5OZPavrVYz2VFw',
    appId: '1:3090220135:ios:3d26a0fd413b7cc0b200c2',
    messagingSenderId: '3090220135',
    projectId: 'advmobprog-firebase-bf756',
    storageBucket: 'advmobprog-firebase-bf756.firebasestorage.app',
    iosBundleId: 'com.example.eugenioAdvmobprog',
  );
}
